export function dashboardHtml(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>Codebase MCP Dashboard</title><style>body{font:15px system-ui;max-width:1000px;margin:2rem auto;padding:1rem}section{border:1px solid #ddd;padding:1rem;margin:1rem 0}.job{border-top:1px solid #eee;padding:.7rem 0}.bar{height:8px;background:#ddd}.bar i{display:block;height:100%;background:#26c}.auth{display:flex;gap:.5rem}.auth input{flex:1}</style></head><body><h1>Codebase MCP Dashboard</h1><div class="auth"><input id="token" type="password" autocomplete="off" placeholder="LOCAL_AUTH_TOKEN"><button id="connect">Connect</button></div><p id="status">Enter the local bearer token to connect.</p><main id="content" hidden><p id="summary"></p><section><h2>Running</h2><div id="running"></div></section><section><h2>Queued</h2><div id="queued"></div></section><section><h2>Recent tasks</h2><div id="recent"></div></section></main><script>
const input=document.querySelector('#token'),status=document.querySelector('#status'),content=document.querySelector('#content');let timer;
const node=(v)=>{const n=document.createElement('span');n.textContent=v??'';return n};
function jobView(j,progress){const e=document.createElement('article');e.className='job';const title=document.createElement('strong');title.textContent=j.kind+' · '+j.path;e.append(title,document.createElement('br'),node(j.state+' · '+j.id));if(progress){const p=document.createElement('p'),total=j.totalFiles||0,done=j.processedFiles||0;p.textContent=done+'/'+total+' files'+(j.currentFile?' · '+j.currentFile:'');e.append(p);const bar=document.createElement('div'),fill=document.createElement('i');bar.className='bar';fill.style.width=(total===0?100:Math.min(100,done/total*100))+'%';bar.append(fill);e.append(bar)}if(j.failureMessage){const f=document.createElement('p');f.textContent=j.failureCode+': '+j.failureMessage;e.append(f)}return e}
function render(d){document.querySelector('#summary').textContent='Running: '+d.runningCount+' · Queued: '+d.queuedCount+' · Max concurrency: '+d.maxConcurrency;[['running',d.activeJobs.filter(j=>j.state==='running'),true],['queued',d.activeJobs.filter(j=>j.state==='queued'),false],['recent',d.recentJobs,false]].forEach(([id,items,p])=>{const box=document.querySelector('#'+id);box.replaceChildren();if(!items.length)box.append(node('No tasks.'));else items.forEach(j=>box.append(jobView(j,p)))});content.hidden=false}
let activeToken='';async function refresh(){const token=activeToken;if(!token)return;try{const r=await fetch('/api/dashboard/jobs',{headers:{Authorization:'Bearer '+token}});if(r.status===401){clearInterval(timer);activeToken='';input.value='';content.hidden=true;status.textContent='Token rejected. Enter a valid local bearer token.';return}if(!r.ok)throw new Error('request failed ('+r.status+')');render(await r.json());status.textContent='Updated '+new Date().toLocaleTimeString()}catch(e){status.textContent='Unable to refresh: '+e.message+' (showing last successful data)'}}
document.querySelector('#connect').onclick=()=>{activeToken=input.value.trim();clearInterval(timer);refresh();timer=setInterval(refresh,2000)};
</script></body></html>`;
}
